### ISSUE TITLE
Update v2.9.2

### ISSUE THREAD

**Issue by SpookyCongee** [Inglix/FasterBiosculpterPod#8]
Whenever you find a moment, I'd appreciate it if you could update this mod to the latest version here on Git. Many thanks in advance.

**Comment by Inglix** [comment]
Sorry I delayed so long getting around to this. I suppose you can thank Ludeon's RimWorld update today that broke my mod and forced me to push an update, which reminded me I hadn't published a release here for a while. 

https://github.com/Inglix/FasterBiosculpterPod/releases/tag/v2.9.3
